name: bitinfo-docs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - julia
  - pyjulia
  - matplotlib-base
  - numpy
  - pooch
  - xarray
  - dask-core
  - jupyterlab
  - netcdf4
  - zarr
  - cfgrib
  - prefect>=1.0.0
  - cmcrameri
  - tqdm
  - sphinx!=4.4.0
  - sphinxcontrib-napoleon
  - sphinx-copybutton
  - sphinx-book-theme
  - myst-nb
  - pip
  - pip:
    - git+https://github.com/rabernat/numcodecs@bitround
    - -e ../.
